variable "project_id" {
  description = "GCP Project ID"
  type        = string
}

variable "region" {
  description = "GCP Region"
  type        = string
  default     = "europe-west3"
}

variable "zenml_server_url" {
  description = "The URL where your ZenML server is hosted. This should be the base URL of the ZenML server, e.g. 'http://zenml.example.com:8080'"
  type        = string

  validation {
    condition     = can(regex("http[s]?://", var.zenml_server_url))
    error_message = "The ZenML server URL must start with 'http://' or 'https://'"
  }
}

variable "zenml_api_key" {
  description = "ZenML service account API key to authenticate with the ZenML server. A ZenML API key can be generated by following the instructions at https://docs.zenml.io/how-to/connecting-to-zenml/connect-with-a-service-account"
  type        = string
  sensitive   = true
}

variable "zenml_api_token" {
  description = "ZenML service account API token to authenticate with the ZenML server. This is only used with by ZenML CLI or dashboard and should not be used to run the Terraform module manually."
  type        = string
  sensitive   = true
  default     = ""
}

variable "zenml_stack_name" {
  description = "A custom name for the ZenML stack that will be registered with the ZenML server"
  type        = string
  default     = ""
}

variable "zenml_stack_deployment" {
  description = "The deployment type for the ZenML stack. Used as a label for the registered ZenML stack."
  type        = string
  default     = "terraform"
}
